### ISSUE TITLE
Freaking LoL clan glitched in our base and took our stuff.

### ISSUE THREAD

**Issue by HomieQuan** [Calytic/cyclone.rust#1]
This is how it goes me and my friend alderous are in our base just chilling after a good raid with wolf. I then go down stairs cause i heard some one out side. So alderous went out side to look around and he started to look and no one was their. so i started to look around at the bottom of our base like inside in the little circle of our base no one was their i mean nothing. Then he said to come out side i walked out stood in door way and then turned around and "LOL" Gangster just appeared in front of me like he teleported in front of me then shot me and my cousin killed him but then another member some how put ladders all the way up no suprise but then got in our locked doors. They are saying that all of our doors where unlocked and that we locked them when admin came but we never unlocked them and we never removed did anything with them both where locked no holes in base and no ladders on out side they freaking glitched in our base then procedded up stairs then glitched through or hacked through the door because it was locked and he some how managed to get through i call bull shit.

**Comment by Calytic** [comment]
We have discovered the means by which this occurred and the parties involved will be held accountable.  Thank you for your feedback.  Closing issue.
